// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (
    id, course_id, slug, title, description_markdown,
    deadline, hard_deadline, max_score, template_repo, repo_naming_pattern,
    auto_request_review_on_pass, requires_defense,
    weight_tests, weight_quality, defence_multiplier, custom_formula, runner
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12,
    $13, $14, $15, $16, $17
)
RETURNING id, course_id, slug, title, description_markdown, deadline, hard_deadline, max_score, template_repo, repo_naming_pattern, auto_request_review_on_pass, requires_defense, weight_tests, weight_quality, defence_multiplier, custom_formula, runner, created_at, updated_at
`

type CreateAssignmentParams struct {
	ID                      string
	CourseID                string
	Slug                    string
	Title                   string
	DescriptionMarkdown     string
	Deadline                pgtype.Timestamp
	HardDeadline            pgtype.Timestamp
	MaxScore                int32
	TemplateRepo            string
	RepoNamingPattern       string
	AutoRequestReviewOnPass bool
	RequiresDefense         bool
	WeightTests             float64
	WeightQuality           float64
	DefenceMultiplier       bool
	CustomFormula           string
	Runner                  string
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.ID,
		arg.CourseID,
		arg.Slug,
		arg.Title,
		arg.DescriptionMarkdown,
		arg.Deadline,
		arg.HardDeadline,
		arg.MaxScore,
		arg.TemplateRepo,
		arg.RepoNamingPattern,
		arg.AutoRequestReviewOnPass,
		arg.RequiresDefense,
		arg.WeightTests,
		arg.WeightQuality,
		arg.DefenceMultiplier,
		arg.CustomFormula,
		arg.Runner,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Slug,
		&i.Title,
		&i.DescriptionMarkdown,
		&i.Deadline,
		&i.HardDeadline,
		&i.MaxScore,
		&i.TemplateRepo,
		&i.RepoNamingPattern,
		&i.AutoRequestReviewOnPass,
		&i.RequiresDefense,
		&i.WeightTests,
		&i.WeightQuality,
		&i.DefenceMultiplier,
		&i.CustomFormula,
		&i.Runner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentById = `-- name: GetAssignmentById :one
SELECT id, course_id, slug, title, description_markdown, deadline, hard_deadline, max_score, template_repo, repo_naming_pattern, auto_request_review_on_pass, requires_defense, weight_tests, weight_quality, defence_multiplier, custom_formula, runner, created_at, updated_at FROM assignments WHERE id = $1
`

func (q *Queries) GetAssignmentById(ctx context.Context, id string) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentById, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Slug,
		&i.Title,
		&i.DescriptionMarkdown,
		&i.Deadline,
		&i.HardDeadline,
		&i.MaxScore,
		&i.TemplateRepo,
		&i.RepoNamingPattern,
		&i.AutoRequestReviewOnPass,
		&i.RequiresDefense,
		&i.WeightTests,
		&i.WeightQuality,
		&i.DefenceMultiplier,
		&i.CustomFormula,
		&i.Runner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignments = `-- name: ListAssignments :many
SELECT id, course_id, slug, title, description_markdown, deadline, hard_deadline, max_score, template_repo, repo_naming_pattern, auto_request_review_on_pass, requires_defense, weight_tests, weight_quality, defence_multiplier, custom_formula, runner, created_at, updated_at FROM assignments
WHERE ($1::text IS NULL OR course_id = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAssignmentsParams struct {
	CourseID *string
	Offset   int32
	Limit    int32
}

func (q *Queries) ListAssignments(ctx context.Context, arg ListAssignmentsParams) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignments, arg.CourseID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Slug,
			&i.Title,
			&i.DescriptionMarkdown,
			&i.Deadline,
			&i.HardDeadline,
			&i.MaxScore,
			&i.TemplateRepo,
			&i.RepoNamingPattern,
			&i.AutoRequestReviewOnPass,
			&i.RequiresDefense,
			&i.WeightTests,
			&i.WeightQuality,
			&i.DefenceMultiplier,
			&i.CustomFormula,
			&i.Runner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
