// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlcgen

import (
	"context"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (id, code, title, description, instructor_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, title, description, instructor_id, vcs_provider_kind, vcs_provider_instance, vcs_target_org, vcs_student_team, vcs_reviewer_team, vcs_reviewer_logins, created_at, updated_at
`

type CreateCourseParams struct {
	ID           string
	Code         string
	Title        string
	Description  string
	InstructorID string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.ID,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.InstructorID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.InstructorID,
		&i.VcsProviderKind,
		&i.VcsProviderInstance,
		&i.VcsTargetOrg,
		&i.VcsStudentTeam,
		&i.VcsReviewerTeam,
		&i.VcsReviewerLogins,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseById = `-- name: GetCourseById :one
SELECT id, code, title, description, instructor_id, vcs_provider_kind, vcs_provider_instance, vcs_target_org, vcs_student_team, vcs_reviewer_team, vcs_reviewer_logins, created_at, updated_at FROM courses WHERE id = $1
`

func (q *Queries) GetCourseById(ctx context.Context, id string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseById, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.InstructorID,
		&i.VcsProviderKind,
		&i.VcsProviderInstance,
		&i.VcsTargetOrg,
		&i.VcsStudentTeam,
		&i.VcsReviewerTeam,
		&i.VcsReviewerLogins,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, code, title, description, instructor_id, vcs_provider_kind, vcs_provider_instance, vcs_target_org, vcs_student_team, vcs_reviewer_team, vcs_reviewer_logins, created_at, updated_at FROM courses
WHERE ($1::text IS NULL OR instructor_id = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListCoursesParams struct {
	InstructorID *string
	Offset       int32
	Limit        int32
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses, arg.InstructorID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.InstructorID,
			&i.VcsProviderKind,
			&i.VcsProviderInstance,
			&i.VcsTargetOrg,
			&i.VcsStudentTeam,
			&i.VcsReviewerTeam,
			&i.VcsReviewerLogins,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
