// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package sqlcgen

import (
	"context"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (id, user_id, course_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, course_id, role, enrolled_at
`

type CreateEnrollmentParams struct {
	ID       string
	UserID   string
	CourseID string
	Role     string
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.ID,
		arg.UserID,
		arg.CourseID,
		arg.Role,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.Role,
		&i.EnrolledAt,
	)
	return i, err
}

const deleteEnrollment = `-- name: DeleteEnrollment :execrows
DELETE FROM enrollments WHERE user_id = $1 AND course_id = $2
`

type DeleteEnrollmentParams struct {
	UserID   string
	CourseID string
}

func (q *Queries) DeleteEnrollment(ctx context.Context, arg DeleteEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnrollment, arg.UserID, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEnrollments = `-- name: ListEnrollments :many
SELECT id, user_id, course_id, role, enrolled_at FROM enrollments
WHERE ($1::text IS NULL OR course_id = $1)
  AND ($2::text IS NULL OR user_id = $2)
ORDER BY enrolled_at DESC
LIMIT $4 OFFSET $3
`

type ListEnrollmentsParams struct {
	CourseID *string
	UserID   *string
	Offset   int32
	Limit    int32
}

func (q *Queries) ListEnrollments(ctx context.Context, arg ListEnrollmentsParams) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, listEnrollments,
		arg.CourseID,
		arg.UserID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enrollment
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.Role,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
