// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaBootstrap struct {
	ID          int16
	Initialized bool
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID           string
	Email        string
	DisplayName  string
	PasswordHash *string
	TelegramID   *string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
