// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_repos.sql

package sqlcgen

import (
	"context"
)

const getStudentRepo = `-- name: GetStudentRepo :one
SELECT id, user_id, assignment_id, provider_kind, provider_instance, full_name, external_id, state, clone_url_https, clone_url_ssh, created_at, updated_at FROM student_repos WHERE user_id = $1 AND assignment_id = $2
`

type GetStudentRepoParams struct {
	UserID       string
	AssignmentID string
}

func (q *Queries) GetStudentRepo(ctx context.Context, arg GetStudentRepoParams) (StudentRepo, error) {
	row := q.db.QueryRow(ctx, getStudentRepo, arg.UserID, arg.AssignmentID)
	var i StudentRepo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AssignmentID,
		&i.ProviderKind,
		&i.ProviderInstance,
		&i.FullName,
		&i.ExternalID,
		&i.State,
		&i.CloneUrlHttps,
		&i.CloneUrlSsh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerStudentRepo = `-- name: RegisterStudentRepo :one
INSERT INTO student_repos (
    id, user_id, assignment_id, provider_kind, provider_instance,
    full_name, external_id, state, clone_url_https, clone_url_ssh
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (user_id, assignment_id) DO UPDATE SET
    provider_kind = EXCLUDED.provider_kind,
    provider_instance = EXCLUDED.provider_instance,
    full_name = EXCLUDED.full_name,
    external_id = EXCLUDED.external_id,
    state = EXCLUDED.state,
    clone_url_https = EXCLUDED.clone_url_https,
    clone_url_ssh = EXCLUDED.clone_url_ssh
RETURNING id, user_id, assignment_id, provider_kind, provider_instance, full_name, external_id, state, clone_url_https, clone_url_ssh, created_at, updated_at
`

type RegisterStudentRepoParams struct {
	ID               string
	UserID           string
	AssignmentID     string
	ProviderKind     int32
	ProviderInstance string
	FullName         string
	ExternalID       int64
	State            string
	CloneUrlHttps    string
	CloneUrlSsh      string
}

func (q *Queries) RegisterStudentRepo(ctx context.Context, arg RegisterStudentRepoParams) (StudentRepo, error) {
	row := q.db.QueryRow(ctx, registerStudentRepo,
		arg.ID,
		arg.UserID,
		arg.AssignmentID,
		arg.ProviderKind,
		arg.ProviderInstance,
		arg.FullName,
		arg.ExternalID,
		arg.State,
		arg.CloneUrlHttps,
		arg.CloneUrlSsh,
	)
	var i StudentRepo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AssignmentID,
		&i.ProviderKind,
		&i.ProviderInstance,
		&i.FullName,
		&i.ExternalID,
		&i.State,
		&i.CloneUrlHttps,
		&i.CloneUrlSsh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
