// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vcs_identities.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVCSIdentity = `-- name: DeleteVCSIdentity :execrows
DELETE FROM vcs_identities
WHERE user_id = $1 AND provider_kind = $2 AND provider_instance = $3
`

type DeleteVCSIdentityParams struct {
	UserID           string
	ProviderKind     int32
	ProviderInstance string
}

func (q *Queries) DeleteVCSIdentity(ctx context.Context, arg DeleteVCSIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVCSIdentity, arg.UserID, arg.ProviderKind, arg.ProviderInstance)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVCSIdentities = `-- name: ListVCSIdentities :many
SELECT user_id, provider_kind, provider_instance, external_user_id, external_login, access_token, refresh_token, expires_at, token_valid, linked_at FROM vcs_identities WHERE user_id = $1 ORDER BY linked_at DESC
`

func (q *Queries) ListVCSIdentities(ctx context.Context, userID string) ([]VcsIdentity, error) {
	rows, err := q.db.Query(ctx, listVCSIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VcsIdentity
	for rows.Next() {
		var i VcsIdentity
		if err := rows.Scan(
			&i.UserID,
			&i.ProviderKind,
			&i.ProviderInstance,
			&i.ExternalUserID,
			&i.ExternalLogin,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.TokenValid,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVCSIdentity = `-- name: UpsertVCSIdentity :one
INSERT INTO vcs_identities (
    user_id, provider_kind, provider_instance, external_user_id, external_login,
    access_token, refresh_token, expires_at, token_valid
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, TRUE
)
ON CONFLICT (user_id, provider_kind, provider_instance) DO UPDATE SET
    external_user_id = EXCLUDED.external_user_id,
    external_login = EXCLUDED.external_login,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expires_at = EXCLUDED.expires_at,
    token_valid = TRUE,
    linked_at = now()
RETURNING user_id, provider_kind, provider_instance, external_user_id, external_login, access_token, refresh_token, expires_at, token_valid, linked_at
`

type UpsertVCSIdentityParams struct {
	UserID           string
	ProviderKind     int32
	ProviderInstance string
	ExternalUserID   int64
	ExternalLogin    string
	AccessToken      *string
	RefreshToken     *string
	ExpiresAt        pgtype.Timestamp
}

func (q *Queries) UpsertVCSIdentity(ctx context.Context, arg UpsertVCSIdentityParams) (VcsIdentity, error) {
	row := q.db.QueryRow(ctx, upsertVCSIdentity,
		arg.UserID,
		arg.ProviderKind,
		arg.ProviderInstance,
		arg.ExternalUserID,
		arg.ExternalLogin,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i VcsIdentity
	err := row.Scan(
		&i.UserID,
		&i.ProviderKind,
		&i.ProviderInstance,
		&i.ExternalUserID,
		&i.ExternalLogin,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.TokenValid,
		&i.LinkedAt,
	)
	return i, err
}
